
CREATE DATABASE COVID_SLAYER;
USE COVID_SLAYER;

CREATE TABLE IF NOT EXISTS `USERS` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(50) DEFAULT NULL,
    `EMAIL` VARCHAR(50) DEFAULT NULL,
    `PASSWORD` VARCHAR(50) DEFAULT NULL,
    `AGE` INT(11) UNSIGNED NOT NULL,
    `GENDER` ENUM('MALE', 'FEMALE') DEFAULT 'MALE',
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `GAME_BIBLE` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `GAME_ID` VARCHAR(50) DEFAULT NULL,
    `USER_ID` VARCHAR(50) DEFAULT NULL,
    `STATUS` ENUM('WON', 'LOST') DEFAULT 'WON',
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

CREATE TABLE IF NOT EXISTS `GAME_LOG` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `GAME_ID` VARCHAR(50) DEFAULT NULL,
    `POINT` VARCHAR(10) DEFAULT NULL,
    `PLAYER_TYPE` VARCHAR(50) DEFAULT NULL,
    `ATTACK_TYPE` VARCHAR(50) DEFAULT NULL,
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;